# -*- coding: utf-8 -*-
"""automate_Jamila-Farhana

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vhXg5_9CJlvTCxq3zzR7fAE7m411kYAi
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import RobustScaler
import os


def load_data(input_path: str) -> pd.DataFrame:
    df = pd.read_csv(input_path)
    return df


def preprocess_data(df: pd.DataFrame) -> pd.DataFrame:
    # drop id
    if 'id' in df.columns:
        df = df.drop(columns=['id'])

    # encode target variable
    df['diagnosis'] = df['diagnosis'].map({'M': 1, 'B': 0})

    # separate features and target
    X = df.drop(columns=['diagnosis'])
    y = df['diagnosis']

    # scaling (RobustScaler)
    scaler = RobustScaler()
    X_scaled = scaler.fit_transform(X)
    X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)

    processed_df = pd.concat([X_scaled_df, y.reset_index(drop=True)], axis=1)

    return processed_df


def save_processed_data(df: pd.DataFrame, output_path: str):
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    df.to_csv(output_path, index=False)


def run_pipeline(
    input_path: str = "/breast-cancer_raw.csv",
    output_path: str = "/breast-cancer_processed.csv"
):
    df = load_data(input_path)
    processed_df = preprocess_data(df)
    save_processed_data(processed_df, output_path)


if __name__ == "__main__":
    run_pipeline()